[package]
name = "pixelypse_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "0.21"
rand = "0.8"
libm = "0.2"
kira = "0.8.6"